services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./web/html:/usr/share/nginx/html
      - ./web/reloj:/usr/share/nginx/html/reloj
      - ./nginx/default-https.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    restart: unless-stopped

  sftp:
    image: linuxserver/openssh-server
    container_name: sftp-server
    ports:
      - "2222:2222"
    environment:
      - PUID=1000
      - PGID=1000
      - USER_NAME=usuario
      - USER_PASSWORD=password
      - PASSWORD_ACCESS=true
      - LISTEN_PORT=2222
    volumes:
      - ./web:/config/web
    restart: unless-stopped
